version: "3"
services:
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - metronome-network

  web:
    image: metronomedotsh/metronome:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    command: /bin/sh -c "pnpm --filter @metronome/db.server setup && pnpm --filter @metronome/web start"
    healthcheck:
      test: "curl --fail http://localhost:${APP_PORT}/healthcheck"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - metronome-network

  workers:
    image: metronomedotsh/metronome:latest
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    command: "pnpm --filter @metronome/workers start"
    networks:
      - metronome-network

  cron:
    image: metronomedotsh/metronome:latest
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    command: "pnpm --filter @metronome/cron start"
    networks:
      - metronome-network

  db:
    restart: always
    platform: linux/amd64
    image: "timescale/timescaledb-ha:pg15.3-ts2.11.1"
    environment:
      POSTGRES_USER: "${DB_WRITE_USER}"
      POSTGRES_PASSWORD: "${DB_WRITE_PASSWORD}"
      POSTGRES_DB: "${DB_WRITE_DATABASE}"
      TIMESCALEDB_TELEMETRY: "off"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_WRITE_USER} -d ${DB_WRITE_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["-c", "max_connections=9999"]
    networks:
      - metronome-network
    volumes:
      - "db:/home/postgres/pgdata/data"

  redis:
    restart: always
    image: redis:6.2.6
    command:
      - redis-server
      - --appendonly yes
      - --requirepass
      - "${REDIS_CACHE_PASSWORD}"
    volumes:
      - "redis:/data"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - metronome-network

networks:
  metronome-network:

volumes:
  db:
    driver: local
  redis:
    driver: local
